=pod

=head1 NAME

Zucchini::Contributors - people that helped out along the way

=head1 AUTHOR

Chisel Wright C<< <chiselwright@users.berlios.de> >>

=head1 IDEAS and FEEDBACK

=head2 Kurt vom Walde

General positive feedback.

Numerous functionality suggestions: --config, always_follow, TT options and more.

=head1 INTERFACE

=head2 Jason Tang

Refactoring of ttsite script

=head1 PROJECTS

L<Moose>,
L<Template>

=cut
