#!/usr/bin/env perl;
# vim: ts=8 sts=4 et sw=4 sr sta
use strict;
use warnings;

use Zucchini;

exit;

__END__

=pod

=head1 NAME

zucchini - script to generate and upload template based websites

=head1 DESCRIPTION

TODO

=head1 SYNOPSIS

TODO

=head1 SEE ALSO

Zuccnini

=head1 AUTHOR

Chisel Wright C<< <chiselwright@users.berlios.de> >>

=head1 LICENSE

Copyright 2008 by Chisel Wright

This program is free software; you can redistribute it and/or modify it under
the same terms as Perl itself.

See <http://www.perl.com/perl/misc/Artistic.html>

=cut
